apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: appr
  syncPolicy:
    syncOptions:
      - FluxSubsystem=true
      - CreateNamespace=true
      - AutoCreateFluxResources=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ./infra
    repoURL: https://github.com/DamianBis/tf-controller-helloworld.git
    targetRevision: main