apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prelive-applications
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applications
    repoURL: git@github.com:DamianBis/argo-demo.git
    targetRevision: main
    helm:
      values: |
        environmentName: prelive
