apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prelive
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: prelive
  syncPolicy:
    syncOptions:
      - FluxSubsystem=true
      - CreateNamespace=true
      - AutoCreateFluxResources=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: flux-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: false
    path: applications
    repoURL: https://github.com/DamianBis/argo-demo.git
    targetRevision: main
    helm:      
      releaseName: prelive
      valueFiles:
      - values-prelive.yaml
