# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: backstage-{{ .Values.environmentName }}
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: {{ .Values.environmentName }}
#   syncPolicy:
#     automated:
#       prune: true
#       allowEmpty: true
#       selfHeal: true
#   destination:
#     namespace: argocd
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: Apps/backstage
#     repoURL: git@github.com:DamianBis/argo-demo.git
#     targetRevision: main
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.environmentName }}-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  game.properties: |
    enemy.types=aliens,monsters