---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: {{ .Values.environmentName }}-tf
spec:
  interval: 1m
  url: https://github.com/DamianBis/argo-demo.git
  secretRef:
    name: podinfo-auth
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{ .Values.environmentName }}
spec:
  interval: 1m0s
  path: applications/
  prune: true
  sourceRef:
    kind: GitRepository
    name: {{ .Values.environmentName }}-tf
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: {{ .Values.environmentName }}-tf
spec:
  path: ./applications/tf/
  approvePlan: auto
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: {{ .Values.environmentName }}-tf
  writeOutputsToSecret:
    name: {{ .Values.environmentName }}-outputs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-runner-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-runner-role
subjects:
- kind: ServiceAccount
  name: tf-runner  