apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: merchants-ui-{{ .Values.environmentName }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.environmentName }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: Apps/merchants-ui
    repoURL: git@github.com:DamianBis/argo-demo.git
    targetRevision: main