apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-stuff-{{ .Values.environmentName }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.environmentName }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applicationsasdasdasdasdasdasdasd
    repoURL: ssh://git@github.com:22/DamianBis/argo-demo.git
    targetRevision: main
    helm:
      valueFiles:
      - values-{{ .Values.environmentName }}.yaml